name = "emulation"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "episub"
instances = { min = 3, max = 100, default = 3 }
  [testcases.params]
  ## honest node config
  config_file = { type = "str", desc = "Path containing the network configuration file" }
  peers_to_connect = { type = "int", desc = "The number of peers to connect", default=5 }
  message_rate = { type = "int", desc = "The number of messages to publish per 1 second.", default=100 }
  warmup = { type = "int", desc = "Time to wait for nodes to establish connections before beginning publishing", default=5, unit="sec" }
  run = { type = "int", desc = "Time to run the emulation", default=120, unit="sec" }
